name: CI

on:
  workflow_dispatch:
    inputs:
      url: 
        description: 'Enter the link of the Spotify album, song, or playlist'
        required: true
        default: 'https://open.spotify.com/album/2aoSpTAjFaMvaZeruqnCVv'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
      - name: Install requirements
        run: |
          npm install -g freyr
          curl -Lo file.zip https://github.com/miraclx/atomicparsley/releases/download/20230114.175602.21bde60/AtomicParsleyLinux.zip
          mkdir products
          unzip file.zip -d ./products
          npm install -g freyr
      - name: Downloading
        run:  |
          cd products
          ls
          freyr ${{ inputs.url }}
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: output

          path: ./products
